ALTER TABLE `CHUNG_TU_HANG_HOA` DROP `DON_GIA_NT`;
ALTER TABLE `NGHIEP_VU_KE_TOAN` DROP `SO_TIEN_NT`;

CREATE TABLE `BAO_CAO_TAI_CHINH` ( `MA_BCTC` INT NOT NULL AUTO_INCREMENT , `TIEU_DE` VARCHAR(255) NOT NULL , `LOAI_TG` INT NOT NULL , `BAT_DAU` DATE NOT NULL , `KET_THUC` DATE NOT NULL , `NGUOI_LAP` VARCHAR(255) NOT NULL , `GIAM_DOC` VARCHAR(255) NOT NULL , `NGAY_LAP` DATE NOT NULL , `MA_KKT` INT NOT NULL, PRIMARY KEY (`MA_BCTC`)) ENGINE = InnoDB;
CREATE TABLE `BAO_CAO_TAI_CHINH_CON` ( `MA_BCTC_CON` INT NOT NULL AUTO_INCREMENT, `MA_BCTC` INT NOT NULL , `LOAI_BCTC` INT NOT NULL , PRIMARY KEY (`MA_BCTC_CON`)) ENGINE = InnoDB;
CREATE TABLE `BAO_CAO_TAI_CHINH_CHI_TIET` ( `MA_BCTC_CON` INT NOT NULL , `ASSET_CODE` VARCHAR(10) NOT NULL , `GIA_TRI` DOUBLE NOT NULL , `GIA_TRI_KY_TRUOC` DOUBLE NOT NULL, PRIMARY KEY (`MA_BCTC_CON`, `ASSET_CODE`)) ENGINE = InnoDB;
