SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `HANG_HOA_NHOM` ( `MA_NHOM_HH` INT NOT NULL AUTO_INCREMENT , `KH_NHOM_HH` VARCHAR(255) NOT NULL, `TEN_NHOM_HH` VARCHAR(255) NOT NULL , `MA_NHOM_HH_CHA` INT NULL , PRIMARY KEY (`MA_NHOM_HH`)) ENGINE = InnoDB;
INSERT INTO `HANG_HOA_NHOM` (`TEN_NHOM_HH`, `MA_NHOM_HH_CHA`) VALUES ('Công cụ dụng cụ', NULL), ('Hàng hóa', NULL), ('Nguyên vật liệu', NULL), ('Xăng', 3);

CREATE TABLE `HANG_HOA_DANH_MUC` ( `MA_HH` INT NOT NULL AUTO_INCREMENT , `KH_HH` VARCHAR(255) NOT NULL, `TEN_HH` VARCHAR(255) NOT NULL , `MA_DV` INT NOT NULL , `MA_NHOM_HH` INT NULL , `TINH_CHAT` TINYINT NOT NULL DEFAULT '1', `MO_TA` VARCHAR(255) NULL , `NGUON_GOC` VARCHAR(255) NULL, `THOI_HAN_BH` TINYINT NULL, `MA_KHO` INT NULL , `MA_TK_KHO` VARCHAR(10) NULL , `MA_TK_DT` VARCHAR(10) NULL , `MA_TK_CP` VARCHAR(10) NULL, `MA_TK_CK` VARCHAR(10) NULL, `MA_TK_GG` VARCHAR(10) NULL, `MA_TK_TL` VARCHAR(10) NULL, `TY_LE_CKTM` DOUBLE NULL, `THUE_SUAT_GTGT` DOUBLE NULL, `THUE_SUAT_XK` DOUBLE NULL, `THUE_SUAT_NK` DOUBLE NULL, `THUE_SUAT_TTDB` DOUBLE NULL, PRIMARY KEY (`MA_HH`)) ENGINE = InnoDB;
INSERT INTO `HANG_HOA_DANH_MUC` (`KH_HH`, `TEN_HH`, `MA_DV`, `MA_NHOM_HH`) VALUES ('TOYOTA', 'Toyota', 1, 2), ('XNG92', 'Xăng 92', 7, 4);

CREATE TABLE `HANG_HOA_DON_VI` ( `MA_DV` INT NOT NULL AUTO_INCREMENT , `TEN_DV` VARCHAR(50) NOT NULL , `MO_TA` VARCHAR(255) NULL , PRIMARY KEY (`MA_DV`)) ENGINE = InnoDB;
INSERT INTO `HANG_HOA_DON_VI` (`TEN_DV`, `MO_TA`) VALUES ('Chiếc', NULL), ('Cm', 'Centimet'), ('Dm', 'Decimet'), ('Gói', NULL), ('Cái', NULL), ('Lọ', NULL);

CREATE TABLE `HANG_HOA_KHO` ( `MA_KHO` INT NOT NULL AUTO_INCREMENT , `KH_KHO` VARCHAR(255) NOT NULL, `TEN_KHO` VARCHAR(255) NOT NULL , `DIA_CHI` VARCHAR(255) NULL , `MA_TK` VARCHAR(10) NULL, `MO_TA` VARCHAR(255) NULL , PRIMARY KEY (`MA_KHO`)) ENGINE = InnoDB;
INSERT INTO `HANG_HOA_KHO` (`MA_KHO`, `KH_KHO`, `TEN_KHO`, `DIA_CHI`, `MA_TK`, `MO_TA`) VALUES ('0', 'KHOMACDINH', 'Kho mặc định', 'Kho mặc định', NULL, NULL);

CREATE TABLE `HANG_HOA_KHO_HANG` (`MA_HH` INT NOT NULL , `MA_KHO` INT NOT NULL , `MA_GIA` INT NOT NULL, `MA_LO` INT NULL , `SO_LUONG` INT NOT NULL DEFAULT '0' , `NGAY_TAO` DATE NOT NULL, `NGAY_SUA` DATE NOT NULL, `MA_NGUOI_SUA` INT NULL, PRIMARY KEY (`MA_HH`, `MA_KHO`, `MA_GIA`)) ENGINE = InnoDB;
CREATE TABLE `HANG_HOA_GIA` ( `MA_GIA` INT NOT NULL AUTO_INCREMENT , `MA_HH` INT NOT NULL , `DON_GIA` DOUBLE NOT NULL DEFAULT '0' , `NGAY_TAO` DATE NOT NULL, PRIMARY KEY (`MA_GIA`)) ENGINE = InnoDB;

