-- INSERT INTO `CAU_HINH` (`MA`, `TEN`, `GIA_TRI`, `NHOM`) VALUES ('TAI_KHOAN_CONG_NO', 'Tài khoản công nợ', '131;141;331;334', '3'), ('TAI_KHOAN_KHO_VTHH', 'Tài khoản kho vật tư hàng hóa', '152;153;154;155;156', '3');

ALTER TABLE `CHUNG_TU_HANG_HOA` DROP PRIMARY KEY, ADD PRIMARY KEY(`MA_CT`, `MA_HH`, `MA_KHO`, `MA_GIA_KHO`, `CHIEU`);
ALTER TABLE `NGHIEP_VU_KE_TOAN` ADD `SO_TIEN_NT` DOUBLE NOT NULL DEFAULT '0' AFTER `SO_TIEN`;