CREATE TABLE `BAO_CAO_TAI_CHINH_KY_KPI` ( `MA_BCTC` INT NOT NULL , `MA_KY_KPI` INT NOT NULL , PRIMARY KEY (`MA_BCTC`, `MA_KY_KPI`)) ENGINE = InnoDB;

INSERT INTO `CAU_HINH` (`MA`, `TEN`, `GIA_TRI`, `NHOM`) VALUES ('MST', 'Mã số thuế', '1234567890', 1);
