INSERT INTO `CAU_HINH` (`MA`, `TEN`, `GIA_TRI`, `NHOM`) VALUES ('TAI_KHOAN_TIEN_MAT', 'Tài khoản tiền mặt', '111', '3'), ('TAI_KHOAN_TIEN_GUI', 'Tài khoản tiền gửi ngân hàng', '112', '3');

ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `NO_DAU_KY_NT` DOUBLE NOT NULL DEFAULT '0' AFTER `NO_DAU_KY`;
ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `CO_DAU_KY_NT` DOUBLE NOT NULL DEFAULT '0' AFTER `CO_DAU_KY`;
ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `NO_CUOI_KY_NT` DOUBLE NOT NULL DEFAULT '0' AFTER `NO_CUOI_KY`;
ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `CO_CUOI_KY_NT` DOUBLE NOT NULL DEFAULT '0' AFTER `CO_CUOI_KY`;
ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `LOAI_TIEN` VARCHAR(10) NOT NULL DEFAULT 'VND' AFTER `CO_CUOI_KY_NT`;