SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `LINH_VUC` ( `MA_LV` INT NOT NULL AUTO_INCREMENT , `TEN_LV` VARCHAR(255) NOT NULL , `MA_LV_CHA` INT NULL , `MO_TA` VARCHAR(255) NULL , PRIMARY KEY (`MA_LV`)) ENGINE = InnoDB;
INSERT INTO `LINH_VUC` (`TEN_LV`, `MO_TA`) VALUES ('Tài chính','');
INSERT INTO `LINH_VUC` (`TEN_LV`, `MO_TA`) VALUES ('Nhân sự','');

CREATE TABLE `NGHIEP_VU` ( `MA_NV` INT NOT NULL AUTO_INCREMENT , `TEN_NV` VARCHAR(255) NOT NULL , `MO_TA` VARCHAR(500) NULL , `MA_NV_CHA` INT NULL , `MA_LV` INT NOT NULL , `DO_KHO` INT NOT NULL DEFAULT '1' , PRIMARY KEY (`MA_NV`)) ENGINE = InnoDB;


