-- CREATE TABLE `idigroup`.`KHACH_HANG` ( `MA_KH` VARCHAR(50) NOT NULL , `TEN_KH` VARCHAR(255) NOT NULL , `DIA_CHI` VARCHAR(255) NOT NULL , `MS_THUE` VARCHAR(50) NOT NULL , PRIMARY KEY (`MA_KH`) ) ENGINE = InnoDB;
-- CREATE TABLE `idigroup`.`NGOAI_TE` ( `MA_NT` INT NOT NULL AUTO_INCREMENT , `TEN_NT` VARCHAR(255) NOT NULL , `TY_GIA` DOUBLE NOT NULL , PRIMARY KEY (`MA_NT`) ) ENGINE = InnoDB;
-- CREATE TABLE `idigroup`.`DANH_MUC_CHUNG_TU` ( `MA_CT` INT NOT NULL AUTO_INCREMENT , `TEN_CT` VARCHAR(255) NOT NULL , PRIMARY KEY (`MA_CT`) ) ENGINE = InnoDB;
CREATE TABLE `idigroup`.`DANH_MUC_TAI_KHOAN` ( `MA_TK` VARCHAR(10) NOT NULL , `TEN_TK` VARCHAR(255) NOT NULL , `MA_TK_CHA` VARCHAR(10) NULL , `SO_DU` TINYINT NOT NULL DEFAULT 1) ENGINE = InnoDB;
-- BẢNG DƯỚI NÀY CHƯA RÕ KỲ NÀO ?
-- CREATE TABLE `idigroup`.`TAI_KHOAN_DAU_KY` ( `MA_TK` VARCHAR(10) NOT NULL , `NO_DK` DOUBLE NULL , `CO_DK` DOUBLE NULL , PRIMARY KEY (`MA_TK`) ) ENGINE = InnoDB;



