CREATE TABLE `NGHIEP_VU_KE_TOAN_1` ( `MA_CT` INT NOT NULL , `MA_HH` INT NOT NULL , `MA_KC` INT NOT NULL , `MA_TK_NO` VARCHAR(10) NOT NULL , `MA_TK_CO` VARCHAR(10) NOT NULL , `SO_TIEN` DOUBLE NOT NULL , `LY_DO` VARCHAR(255) NOT NULL , `LOAI_TK_NO` TINYINT NULL, `THUE_SUAT_NO` DOUBLE NULL, `LOAI_TK_CO` TINYINT NULL, `THUE_SUAT_CO` DOUBLE NULL, PRIMARY KEY (`MA_CT`, `MA_HH`, `MA_KC`)) ENGINE = InnoDB;

CREATE TABLE `HANG_HOA_DON_VI_CHI_TIET` ( `MA_HH` INT NOT NULL , `MA_DV` INT NOT NULL , BOOLEAN NOT NULL DEFAULT FALSE , `TY_LE` DOUBLE NOT NULL, PRIMARY KEY (`MA_HH`, `MA_DV`) ) ENGINE = InnoDB;

