CREATE TABLE `idigroup`.`KY_KE_TOAN` ( `MA_KKT` INT NOT NULL AUTO_INCREMENT , `TEN_KKT` VARCHAR(255) NOT NULL , `BAT_DAU` DATE NOT NULL , `KET_THUC` DATE NOT NULL , `TRANG_THAI` TINYINT NOT NULL , `MAC_DINH` TINYINT NOT NULL, PRIMARY KEY (`MA_KKT`)) ENGINE = InnoDB;
CREATE TABLE `idigroup`.`KY_KE_TOAN_SO_DU` (`MA_KKT` INT NOT NULL , `MA_TK` VARCHAR(10) NOT NULL , `MA_DT` INT NULL, `NO_DAU_KY` DOUBLE NULL, `CO_DAU_KY` DOUBLE NULL, `NO_CUOI_KY` DOUBLE NULL, `CO_CUOI_KY` DOUBLE NULL, PRIMARY KEY (`MA_KKT`, `MA_TK`)) ENGINE = InnoDB;

CREATE TABLE `idigroup`.`NGHIEP_VU_KE_TOAN` ( `MA_NVKT` INT NOT NULL AUTO_INCREMENT , `MA_TK` VARCHAR(10) NOT NULL ,  `SO_TIEN` double NOT NULL, `SO_DU` TINYINT(1) NOT NULL DEFAULT '-1', `LY_DO` VARCHAR(255) NULL, `ASSET_CODE` VARCHAR(10) NULL, PRIMARY KEY (`MA_NVKT`) ) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE `idigroup`.`CHUNG_TU_HANG_HOA` ( `MA_CT` INT NOT NULL , `MA_HH` INT NOT NULL ,  `MA_KHO` INT NULL, `SO_LUONG_CT` DOUBLE NULL, `SO_LUONG_TN` DOUBLE NULL, `DON_GIA` DOUBLE NULL, `MA_GIA_KHO` INT NOT NULL, `CHIEU` TINYINT NOT NULL DEFAULT '1', PRIMARY KEY( `MA_CT`, `MA_HH`)) ENGINE = InnoDB;
CREATE TABLE `idigroup`.`CHUNG_TU_NVKT` ( `MA_CT` INT NOT NULL , `MA_HH` INT NULL , `MA_NVKT` INT NOT NULL, `LOAI_TK` TINYINT NULL, `THUE_SUAT` DOUBLE NULL ) ENGINE = InnoDB;

-- Bảng đối tác có thể thay thế bảng khách hàng/nhà cung cấp, nên bảng khach_hang và nha_cung_cap sau này có thể xóa đi
-- CREATE TABLE `idigroup`.DOI_TAC ( `MA_DT` INT NOT NULL AUTO_INCREMENT , `TEN_DT` VARCHAR(255) NOT NULL , `MA_THUE` VARCHAR(100) NOT NULL , `DIA_CHI` VARCHAR(255) NOT NULL , `EMAIL` VARCHAR(100) NOT NULL , `SDT` VARCHAR(20) NOT NULL , `WEBSITE` VARCHAR(255) NOT NULL, PRIMARY KEY (`MA_DT`) ) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
-- INSERT INTO `doi_tac` (`MA_DT`, `TEN_DT`, `MA_THUE`, `DIA_CHI`, `EMAIL`, `SDT`, `WEBSITE`) VALUES(1, 'Khách vãng lai', '', '', '', '', '');

ALTER TABLE `tai_khoan_danh_muc` ADD `MA_TK_NH` INT NULL AFTER `SO_DU`;
ALTER TABLE `chung_tu` ADD `MA_KHO` INT NULL AFTER `NGUOI_NOP`;
ALTER TABLE `chung_tu` ADD `NGAY_TAO` DATE NULL AFTER `MA_KHO`, ADD `NGAY_SUA` DATE NULL AFTER `NGAY_TAO`;
ALTER TABLE `chung_tu` ADD `TINH_CHAT` TINYINT NOT NULL DEFAULT '0' AFTER `LOAI_CT`;
ALTER TABLE `chung_tu` ADD `TRANG_THAI` TINYINT NULL AFTER `NGAY_SUA`;

ALTER TABLE `chung_tu_nvkt` ADD `NHOM_DK` TINYINT NOT NULL DEFAULT '0' AFTER `MA_NVKT`;
ALTER TABLE `chung_tu` ADD `NGAY_TT` DATE NULL AFTER `NGAY_SUA`;
ALTER TABLE `tai_khoan_danh_muc` ADD `LUONG_TINH` BOOLEAN NOT NULL DEFAULT FALSE AFTER `MA_TK_NH`;

CREATE TABLE `idigroup`.`BUT_TOAN_KET_CHUYEN` ( `MA_KC` INT NOT NULL AUTO_INCREMENT , `TEN_KC` VARCHAR(255) NOT NULL , `MA_TK_NO` VARCHAR(10) NOT NULL , `MA_TK_CO` INT VARCHAR(10) NOT NULL , `CONG_THUC` VARCHAR(255) NOT NULL, `MO_TA` VARCHAR(500) NULL, `THU_TU` TINYINT NOT NULL, `LOAI_KC` TINYINT NOT NULL, PRIMARY KEY (`MA_KC`)) ENGINE = InnoDB;
ALTER TABLE `chung_tu_nvkt` ADD `MA_KC` INT NULL AFTER `MA_HH`;

ALTER TABLE `chung_tu` CHANGE `NGAY_LAP` `NGAY_LAP` DATE NULL;
-- DROP TABLE `CHUNG_TU_TAI_KHOAN`