SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

ALTER TABLE `HANG_HOA_DANH_MUC` ADD `NGUON_GOC` VARCHAR(255) NULL AFTER `MA_TK_CP`, ADD `THOI_HAN_BH` TINYINT NULL AFTER `NGUON_GOC`, ADD `MA_TK_CK` VARCHAR(10) NULL AFTER `THOI_HAN_BH`, ADD `MA_TK_GG` VARCHAR(10) NULL AFTER `MA_TK_CK`, ADD `MA_TK_TL` VARCHAR(10) NULL AFTER `MA_TK_GG`, ADD `TY_LE_CKTM` DOUBLE NULL AFTER `MA_TK_TL`, ADD `THUE_SUAT_GTGT` DOUBLE NULL DEFAULT '10' AFTER `TY_LE_CKTM`, ADD `THUE_SUAT_XK` DOUBLE NULL AFTER `THUE_SUAT_GTGT`, ADD `THUE_SUAT_NK` DOUBLE NULL AFTER `THUE_SUAT_XK`, ADD `THUE_SUAT_TTDB` DOUBLE NULL AFTER `THUE_SUAT_NK`;
INSERT INTO `HANG_HOA_KHO` (`MA_KHO`, `KH_KHO`, `TEN_KHO`, `DIA_CHI`, `MA_TK`, `MO_TA`) VALUES ('0', 'KHOMACDINH', 'Kho mặc định', 'Kho mặc định', NULL, NULL);

CREATE TABLE `idigroup`.`HANG_HOA_KHO_HANG` (`MA_HH` INT NOT NULL , `MA_KHO` INT NOT NULL , `MA_GIA` INT NOT, `MA_LO` INT NULL , `SO_LUONG` INT NOT NULL DEFAULT '0' , `NGAY_TAO` DATE NOT NULL, `NGAY_SUA` DATE NOT NULL, `MA_NGUOI_SUA` INT NULL, PRIMARY KEY (`MA_HH`, `MA_KHO`, `MA_GIA`)) ENGINE = InnoDB;
CREATE TABLE `idigroup`.`HANG_HOA_GIA` ( `MA_GIA` INT NOT NULL AUTO_INCREMENT , `MA_HH` INT NOT NULL , `DON_GIA` DOUBLE NOT NULL DEFAULT '0' , `NGAY_TAO` DATE NOT NULL, PRIMARY KEY (`MA_GIA`)) ENGINE = InnoDB;

