ALTER TABLE `KHACH_HANG` ADD `KH_KH` VARCHAR(255) NOT NULL AFTER `MA_KH`;
ALTER TABLE `KHACH_HANG` ADD UNIQUE(`KH_KH`)
ALTER TABLE `NHA_CUNG_CAP` ADD `KH_NCC` VARCHAR(255) NOT NULL AFTER `MA_NCC`;
ALTER TABLE `NHA_CUNG_CAP` ADD UNIQUE(`KH_NCC`)





