CREATE TABLE `idigroup`.`KY_KE_TOAN` ( `MA_KKT` INT NOT NULL AUTO_INCREMENT , `TEN_KKT` VARCHAR(255) NOT NULL , `BAT_DAU` DATE NOT NULL , `KET_THUC` DATE NOT NULL , `TRANG_THAI` TINYINT NOT NULL , PRIMARY KEY (`MA_KKT`)) ENGINE = InnoDB;

CREATE TABLE `idigroup`.`KY_KE_TOAN_SO_DU` ( `MA_SO_DU` INT NOT NULL AUTO_INCREMENT , `MA_KKT` INT NOT NULL , `LOAI_SO_DU` TINYINT NOT NULL , `MA_TK` VARCHAR(10) NULL , `MA_DT` INT NULL , `SO_DU` TINYINT NOT NULL , `SO_TIEN` DOUBLE NOT NULL , PRIMARY KEY (`MA_SO_DU`)) ENGINE = InnoDB;

ALTER TABLE `tai_khoan_danh_muc` ADD `MA_TK_NH` INT NULL AFTER `SO_DU`;