SELECT CDKTKQ.ASSET_CODE, CDKTKQ.MA_TK, CDKTKQ.SO_DU, SUM(CDKTKQ.SO_TIEN) AS SO_TIEN 
FROM ( 
	SELECT CDKT.ASSET_CODE, CDKT.MA_TK, NVKT.SO_DU, NVKT.SO_TIEN FROM CHUNG_TU AS CT, CHUNG_TU_NVKT AS CTNVKT, NGHIEP_VU_KE_TOAN AS NVKT, CDKT_TAIKHOAN AS CDKT 
	WHERE CT.MA_CT=CTNVKT.MA_CT AND CTNVKT.MA_NVKT=NVKT.MA_NVKT AND SUBSTRING(NVKT.MA_TK, 1, LENGTH(CDKT.MA_TK))=CDKT.MA_TK 
		AND NVKT.SO_DU=CDKT.SO_DU AND CT.NGAY_HT >= '2018-6-01' AND CT.NGAY_HT <= '2018-7-31' 
		AND ((CDKT.ASSET_CODE='112' AND ((CDKT.MA_TK='1281' AND ) OR (CDKT.MA_TK='1288' AND ))) OR 
		( AND ) OR  
		(CDKT.ASSET_CODE!='112' AND ))
) AS CDKTKQ 
GROUP BY CDKTKQ.ASSET_CODE, CDKTKQ.MA_TK, CDKTKQ.SO_DU