ALTER TABLE `KY_KE_TOAN_SO_DU` ADD `LOAI_DT` TINYINT(1) NULL AFTER `MA_DT`;
ALTER TABLE `KY_KE_TOAN_SO_DU` DROP PRIMARY KEY, ADD PRIMARY KEY(`MA_KKT`,`MA_TK`,`MA_DT`,`LOAI_DT`);

ALTER TABLE `CDKT_TAIKHOAN` ADD `MA_TK_GOC` VARCHAR(10) NOT NULL AFTER `MA_TK`;
UPDATE CDKT_TAIKHOAN SET MA_TK_GOC=MA_TK





