SELECT DUNO.ASSET_CODE, DUNO.MA_TK, DUNO.DAU, (DUNO.SO_TIEN*DUNO.SO_DU+DUCO.SO_TIEN*DUCO.SO_DU)*DUNO.DAU AS SO_TIEN  
FROM (SELECT CDKT.ASSET_CODE, CDKT.MA_TK, NVKT.SO_DU, SUM(NVKT.SO_TIEN) AS SO_TIEN, CDKT.SO_DU AS DAU FROM CHUNG_TU AS CT, CHUNG_TU_NVKT AS CTNVKT, NGHIEP_VU_KE_TOAN AS NVKT, CDKT_TAIKHOAN AS CDKT, TAI_KHOAN_DANH_MUC AS TKDM 
	WHERE CT.MA_CT=CTNVKT.MA_CT AND CTNVKT.MA_NVKT=NVKT.MA_NVKT AND NVKT.MA_TK=TKDM.MA_TK AND SUBSTRING(NVKT.MA_TK, 1, LENGTH(CDKT.MA_TK))=CDKT.MA_TK 
		AND TKDM.LUONG_TINH=0 AND NVKT.SO_DU=-1 AND CT.NGAY_HT >= '2018-1-01' AND CT.NGAY_HT <= '2018-12-31'
	GROUP BY CDKT.ASSET_CODE, CDKT.MA_TK) AS DUNO, 
	(SELECT CDKT.ASSET_CODE, CDKT.MA_TK, NVKT.SO_DU, SUM(NVKT.SO_TIEN) AS SO_TIEN, CDKT.SO_DU AS DAU FROM CHUNG_TU AS CT, CHUNG_TU_NVKT AS CTNVKT, NGHIEP_VU_KE_TOAN AS NVKT, CDKT_TAIKHOAN AS CDKT, TAI_KHOAN_DANH_MUC AS TKDM 
	WHERE CT.MA_CT=CTNVKT.MA_CT AND CTNVKT.MA_NVKT=NVKT.MA_NVKT AND NVKT.MA_TK=TKDM.MA_TK AND SUBSTRING(NVKT.MA_TK, 1, LENGTH(CDKT.MA_TK))=CDKT.MA_TK 
		AND TKDM.LUONG_TINH=0 AND NVKT.SO_DU=1 AND CT.NGAY_HT >= '2018-1-01' AND CT.NGAY_HT <= '2018-12-31'
	GROUP BY CDKT.ASSET_CODE, CDKT.MA_TK) AS DUCO
WHERE DUNO.ASSET_CODE=DUCO.ASSET_CODE AND DUNO.MA_TK=DUCO.MA_TK 
UNION 
SELECT CDKT.ASSET_CODE, CDKT.MA_TK, CDKT.SO_DU, SUM(NVKT.SO_TIEN) AS SO_TIEN 
FROM CHUNG_TU AS CT, CHUNG_TU_NVKT AS CTNVKT, NGHIEP_VU_KE_TOAN AS NVKT, CDKT_TAIKHOAN AS CDKT, TAI_KHOAN_DANH_MUC AS TKDM 
WHERE CT.MA_CT=CTNVKT.MA_CT AND CTNVKT.MA_NVKT=NVKT.MA_NVKT AND NVKT.MA_TK=TKDM.MA_TK AND SUBSTRING(NVKT.MA_TK, 1, LENGTH(CDKT.MA_TK))=CDKT.MA_TK 
		AND TKDM.LUONG_TINH=1 AND CT.NGAY_HT >= '2018-1-01' AND CT.NGAY_HT <= '2018-12-31'
	GROUP BY CDKT.ASSET_CODE, CDKT.MA_TK
